linters-settings:
  goconst:
    min-len: 5
    min-occurrences: 4
  misspell:
    locale: US
  gosec:
    excludes: [G402]

linters:
  enable-all: true
  disable:
    - depguard
    - exhaustruct
    - godox     # TODOs is ok
    - mnd       # nice to have
    - nlreturn  # nice to have
    - paralleltest # for now we have only one integration (not parallelable) test
    - tenv
    - varnamelen
    - wrapcheck # nice to have
    - wsl
