run:
  deadline: 1m
  tests: false
  #skip-files:
  #  - ".*\\.gen\\.go"

linters-settings:
  golint:
    min-confidence: 0
  maligned:
    suggest-new: true
  goconst:
    min-len: 5
    min-occurrences: 4
  misspell:
    locale: US

linters:
  enable-all: true
  disable:
    - depguard
    - exhaustruct
    - gosec     # must be turned on
    - lll       # nice to have
    - mnd       # nice to have
    - nlreturn  # nice to have
    - tenv
    - varnamelen
    - wrapcheck # nice to have
    - wsl
