linters-settings:
  goconst:
    min-len: 5
    min-occurrences: 4
  lll:
    line-length: 150
  misspell:
    locale: US
  gosec:
    excludes: [G402]
  ireturn:
    allow:
      - context.Context
      - error
      - io.(Reader|Writer)
      - io.(Read|Write)Closer

linters:
  enable-all: true
  disable:
    - depguard
    - exhaustruct
    - godox     # TODOs is ok
    - mnd       # nice to have
    - nlreturn  # nice to have
    - paralleltest # for now we have only one integration (not parallelable) test
    - tenv
    - varnamelen
    - wsl

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - wrapcheck  # allow naked errors in tests
        - fatcontext # ok in nested tests
        - unparam    # not a crime in tests
