version: "2"
linters:
  default: all
  disable:
    - exhaustruct
    - godox
    - mnd
    - nlreturn
    - paralleltest
    - revive
    - varnamelen
    - wsl
  settings:
    goconst:
      min-len: 5
      min-occurrences: 4
    gosec:
      excludes:
        - G402
    ireturn:
      allow:
        - context.Context
        - error
        - io.(Reader|Writer)
        - io.(Read|Write)Closer
    lll:
      line-length: 150
    misspell:
      locale: US
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/quic-go/quic-go
            - github.com/urfave/cli/v3
  exclusions:
    rules:
      - path: _test.go
        linters:
          - fatcontext
          - unparam
          - wrapcheck
      - source: "^\\s*defer\\s+"
        linters:
          - errcheck
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
